# Generated by Django 5.0.4 on 2024-04-21 16:37

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntariado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('celular', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('endereço', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=50)),
                ('profissão', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('p', 'Pendente'), ('a', 'Aprovado'), ('r', 'Recusado')], default='p', max_length=1)),
            ],
            options={
                'verbose_name': 'Inscrição voluntario',
                'verbose_name_plural': 'Inscrição voluntarios',
            },
        ),
    ]
